# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ODIzZDFhMDM3YTM2NDEzNmIyNWZlMzhkMThjYWE5ZTU2ODJkNjk2NDhlNzZjZDA1ODJmNzBhMWU2MWI2ZjBiNmRmMjhmZDI5YTg3NzliZjRiNDgyZDc0ZDI4YTg1OGY3OGY0ZGU4YTJkMmE3MDgxMjE1ZGYzYjcwYzU5N2U4ZjE=
