package com.mycompany.playmatch.domain;

import static com.mycompany.playmatch.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class CalendarioEventoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarioEventoAllPropertiesEquals(CalendarioEvento expected, CalendarioEvento actual) {
        assertCalendarioEventoAutoGeneratedPropertiesEquals(expected, actual);
        assertCalendarioEventoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarioEventoAllUpdatablePropertiesEquals(CalendarioEvento expected, CalendarioEvento actual) {
        assertCalendarioEventoUpdatableFieldsEquals(expected, actual);
        assertCalendarioEventoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarioEventoAutoGeneratedPropertiesEquals(CalendarioEvento expected, CalendarioEvento actual) {
        assertThat(actual)
            .as("Verify CalendarioEvento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarioEventoUpdatableFieldsEquals(CalendarioEvento expected, CalendarioEvento actual) {
        assertThat(actual)
            .as("Verify CalendarioEvento relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getCalendario()).as("check calendario").isEqualTo(expected.getCalendario()))
            .satisfies(a ->
                assertThat(a.getCalendarioContentType()).as("check calendario content type").isEqualTo(expected.getCalendarioContentType())
            )
            .satisfies(a ->
                assertThat(a.getFechaEvento())
                    .as("check fechaEvento")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaEvento())
            )
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarioEventoUpdatableRelationshipsEquals(CalendarioEvento expected, CalendarioEvento actual) {
        assertThat(actual)
            .as("Verify CalendarioEvento relationships")
            .satisfies(a -> assertThat(a.getTorneo()).as("check torneo").isEqualTo(expected.getTorneo()));
    }
}
