package com.mycompany.playmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CalificacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalificacionAllPropertiesEquals(Calificacion expected, Calificacion actual) {
        assertCalificacionAutoGeneratedPropertiesEquals(expected, actual);
        assertCalificacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalificacionAllUpdatablePropertiesEquals(Calificacion expected, Calificacion actual) {
        assertCalificacionUpdatableFieldsEquals(expected, actual);
        assertCalificacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalificacionAutoGeneratedPropertiesEquals(Calificacion expected, Calificacion actual) {
        assertThat(actual)
            .as("Verify Calificacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalificacionUpdatableFieldsEquals(Calificacion expected, Calificacion actual) {
        assertThat(actual)
            .as("Verify Calificacion relevant properties")
            .satisfies(a -> assertThat(a.getPuntaje()).as("check puntaje").isEqualTo(expected.getPuntaje()))
            .satisfies(a -> assertThat(a.getComentario()).as("check comentario").isEqualTo(expected.getComentario()))
            .satisfies(a -> assertThat(a.getFechaCalificacion()).as("check fechaCalificacion").isEqualTo(expected.getFechaCalificacion()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalificacionUpdatableRelationshipsEquals(Calificacion expected, Calificacion actual) {
        assertThat(actual)
            .as("Verify Calificacion relationships")
            .satisfies(a -> assertThat(a.getTorneo()).as("check torneo").isEqualTo(expected.getTorneo()))
            .satisfies(a -> assertThat(a.getAutor()).as("check autor").isEqualTo(expected.getAutor()));
    }
}
