package com.mycompany.playmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConvocatoriaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConvocatoriaAllPropertiesEquals(Convocatoria expected, Convocatoria actual) {
        assertConvocatoriaAutoGeneratedPropertiesEquals(expected, actual);
        assertConvocatoriaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConvocatoriaAllUpdatablePropertiesEquals(Convocatoria expected, Convocatoria actual) {
        assertConvocatoriaUpdatableFieldsEquals(expected, actual);
        assertConvocatoriaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConvocatoriaAutoGeneratedPropertiesEquals(Convocatoria expected, Convocatoria actual) {
        assertThat(actual)
            .as("Verify Convocatoria auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConvocatoriaUpdatableFieldsEquals(Convocatoria expected, Convocatoria actual) {
        assertThat(actual)
            .as("Verify Convocatoria relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getFechaPublicacion()).as("check fechaPublicacion").isEqualTo(expected.getFechaPublicacion()))
            .satisfies(a ->
                assertThat(a.getFechaInicioInscripcion()).as("check fechaInicioInscripcion").isEqualTo(expected.getFechaInicioInscripcion())
            )
            .satisfies(a ->
                assertThat(a.getFechaFinInscripcion()).as("check fechaFinInscripcion").isEqualTo(expected.getFechaFinInscripcion())
            )
            .satisfies(a -> assertThat(a.getCupos()).as("check cupos").isEqualTo(expected.getCupos()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConvocatoriaUpdatableRelationshipsEquals(Convocatoria expected, Convocatoria actual) {
        assertThat(actual)
            .as("Verify Convocatoria relationships")
            .satisfies(a -> assertThat(a.getTorneo()).as("check torneo").isEqualTo(expected.getTorneo()));
    }
}
