package com.mycompany.playmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CuentaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaAllPropertiesEquals(Cuenta expected, Cuenta actual) {
        assertCuentaAutoGeneratedPropertiesEquals(expected, actual);
        assertCuentaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaAllUpdatablePropertiesEquals(Cuenta expected, Cuenta actual) {
        assertCuentaUpdatableFieldsEquals(expected, actual);
        assertCuentaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaAutoGeneratedPropertiesEquals(Cuenta expected, Cuenta actual) {
        assertThat(actual)
            .as("Verify Cuenta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaUpdatableFieldsEquals(Cuenta expected, Cuenta actual) {
        assertThat(actual)
            .as("Verify Cuenta relevant properties")
            .satisfies(a -> assertThat(a.getFechaNacimiento()).as("check fechaNacimiento").isEqualTo(expected.getFechaNacimiento()))
            .satisfies(a -> assertThat(a.getNumeroDocumento()).as("check numeroDocumento").isEqualTo(expected.getNumeroDocumento()))
            .satisfies(a -> assertThat(a.getCorreo()).as("check correo").isEqualTo(expected.getCorreo()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getDireccion()).as("check direccion").isEqualTo(expected.getDireccion()))
            .satisfies(a -> assertThat(a.getFoto()).as("check foto").isEqualTo(expected.getFoto()))
            .satisfies(a -> assertThat(a.getFotoContentType()).as("check foto content type").isEqualTo(expected.getFotoContentType()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaUpdatableRelationshipsEquals(Cuenta expected, Cuenta actual) {
        assertThat(actual)
            .as("Verify Cuenta relationships")
            .satisfies(a -> assertThat(a.getTipoDocumento()).as("check tipoDocumento").isEqualTo(expected.getTipoDocumento()));
    }
}
