package com.mycompany.playmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EncuestaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestaAllPropertiesEquals(Encuesta expected, Encuesta actual) {
        assertEncuestaAutoGeneratedPropertiesEquals(expected, actual);
        assertEncuestaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestaAllUpdatablePropertiesEquals(Encuesta expected, Encuesta actual) {
        assertEncuestaUpdatableFieldsEquals(expected, actual);
        assertEncuestaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestaAutoGeneratedPropertiesEquals(Encuesta expected, Encuesta actual) {
        assertThat(actual)
            .as("Verify Encuesta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestaUpdatableFieldsEquals(Encuesta expected, Encuesta actual) {
        assertThat(actual)
            .as("Verify Encuesta relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getOpcion1()).as("check opcion1").isEqualTo(expected.getOpcion1()))
            .satisfies(a -> assertThat(a.getOpcion2()).as("check opcion2").isEqualTo(expected.getOpcion2()))
            .satisfies(a -> assertThat(a.getOpcion3()).as("check opcion3").isEqualTo(expected.getOpcion3()))
            .satisfies(a -> assertThat(a.getOpcion4()).as("check opcion4").isEqualTo(expected.getOpcion4()))
            .satisfies(a -> assertThat(a.getVotosOpcion1()).as("check votosOpcion1").isEqualTo(expected.getVotosOpcion1()))
            .satisfies(a -> assertThat(a.getVotosOpcion2()).as("check votosOpcion2").isEqualTo(expected.getVotosOpcion2()))
            .satisfies(a -> assertThat(a.getVotosOpcion3()).as("check votosOpcion3").isEqualTo(expected.getVotosOpcion3()))
            .satisfies(a -> assertThat(a.getVotosOpcion4()).as("check votosOpcion4").isEqualTo(expected.getVotosOpcion4()))
            .satisfies(a -> assertThat(a.getFechaInicio()).as("check fechaInicio").isEqualTo(expected.getFechaInicio()))
            .satisfies(a -> assertThat(a.getFechaFin()).as("check fechaFin").isEqualTo(expected.getFechaFin()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestaUpdatableRelationshipsEquals(Encuesta expected, Encuesta actual) {
        assertThat(actual)
            .as("Verify Encuesta relationships")
            .satisfies(a -> assertThat(a.getGrupo()).as("check grupo").isEqualTo(expected.getGrupo()))
            .satisfies(a -> assertThat(a.getTorneo()).as("check torneo").isEqualTo(expected.getTorneo()));
    }
}
