package com.mycompany.playmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GrupoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAllPropertiesEquals(Grupo expected, Grupo actual) {
        assertGrupoAutoGeneratedPropertiesEquals(expected, actual);
        assertGrupoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAllUpdatablePropertiesEquals(Grupo expected, Grupo actual) {
        assertGrupoUpdatableFieldsEquals(expected, actual);
        assertGrupoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAutoGeneratedPropertiesEquals(Grupo expected, Grupo actual) {
        assertThat(actual)
            .as("Verify Grupo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoUpdatableFieldsEquals(Grupo expected, Grupo actual) {
        assertThat(actual)
            .as("Verify Grupo relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getEscudo()).as("check escudo").isEqualTo(expected.getEscudo()))
            .satisfies(a -> assertThat(a.getEscudoContentType()).as("check escudo content type").isEqualTo(expected.getEscudoContentType()))
            .satisfies(a ->
                assertThat(a.getLimiteParticipantes()).as("check limiteParticipantes").isEqualTo(expected.getLimiteParticipantes())
            )
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoUpdatableRelationshipsEquals(Grupo expected, Grupo actual) {
        // empty method
    }
}
