package com.mycompany.playmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InscripcionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscripcionAllPropertiesEquals(Inscripcion expected, Inscripcion actual) {
        assertInscripcionAutoGeneratedPropertiesEquals(expected, actual);
        assertInscripcionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscripcionAllUpdatablePropertiesEquals(Inscripcion expected, Inscripcion actual) {
        assertInscripcionUpdatableFieldsEquals(expected, actual);
        assertInscripcionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscripcionAutoGeneratedPropertiesEquals(Inscripcion expected, Inscripcion actual) {
        assertThat(actual)
            .as("Verify Inscripcion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscripcionUpdatableFieldsEquals(Inscripcion expected, Inscripcion actual) {
        assertThat(actual)
            .as("Verify Inscripcion relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getFechaInscripcion()).as("check fechaInscripcion").isEqualTo(expected.getFechaInscripcion()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscripcionUpdatableRelationshipsEquals(Inscripcion expected, Inscripcion actual) {
        assertThat(actual)
            .as("Verify Inscripcion relationships")
            .satisfies(a -> assertThat(a.getTorneo()).as("check torneo").isEqualTo(expected.getTorneo()))
            .satisfies(a -> assertThat(a.getUsuario()).as("check usuario").isEqualTo(expected.getUsuario()));
    }
}
