package com.mycompany.playmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MensajeGrupoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeGrupoAllPropertiesEquals(MensajeGrupo expected, MensajeGrupo actual) {
        assertMensajeGrupoAutoGeneratedPropertiesEquals(expected, actual);
        assertMensajeGrupoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeGrupoAllUpdatablePropertiesEquals(MensajeGrupo expected, MensajeGrupo actual) {
        assertMensajeGrupoUpdatableFieldsEquals(expected, actual);
        assertMensajeGrupoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeGrupoAutoGeneratedPropertiesEquals(MensajeGrupo expected, MensajeGrupo actual) {
        assertThat(actual)
            .as("Verify MensajeGrupo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeGrupoUpdatableFieldsEquals(MensajeGrupo expected, MensajeGrupo actual) {
        assertThat(actual)
            .as("Verify MensajeGrupo relevant properties")
            .satisfies(a -> assertThat(a.getContenido()).as("check contenido").isEqualTo(expected.getContenido()))
            .satisfies(a -> assertThat(a.getFechaPublicacion()).as("check fechaPublicacion").isEqualTo(expected.getFechaPublicacion()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeGrupoUpdatableRelationshipsEquals(MensajeGrupo expected, MensajeGrupo actual) {
        assertThat(actual)
            .as("Verify MensajeGrupo relationships")
            .satisfies(a -> assertThat(a.getGrupo()).as("check grupo").isEqualTo(expected.getGrupo()))
            .satisfies(a -> assertThat(a.getAutor()).as("check autor").isEqualTo(expected.getAutor()));
    }
}
