package com.mycompany.playmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MiembroGrupoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMiembroGrupoAllPropertiesEquals(MiembroGrupo expected, MiembroGrupo actual) {
        assertMiembroGrupoAutoGeneratedPropertiesEquals(expected, actual);
        assertMiembroGrupoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMiembroGrupoAllUpdatablePropertiesEquals(MiembroGrupo expected, MiembroGrupo actual) {
        assertMiembroGrupoUpdatableFieldsEquals(expected, actual);
        assertMiembroGrupoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMiembroGrupoAutoGeneratedPropertiesEquals(MiembroGrupo expected, MiembroGrupo actual) {
        assertThat(actual)
            .as("Verify MiembroGrupo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMiembroGrupoUpdatableFieldsEquals(MiembroGrupo expected, MiembroGrupo actual) {
        assertThat(actual)
            .as("Verify MiembroGrupo relevant properties")
            .satisfies(a -> assertThat(a.getFechaIngreso()).as("check fechaIngreso").isEqualTo(expected.getFechaIngreso()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getEsAdministrador()).as("check esAdministrador").isEqualTo(expected.getEsAdministrador()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMiembroGrupoUpdatableRelationshipsEquals(MiembroGrupo expected, MiembroGrupo actual) {
        assertThat(actual)
            .as("Verify MiembroGrupo relationships")
            .satisfies(a -> assertThat(a.getGrupo()).as("check grupo").isEqualTo(expected.getGrupo()))
            .satisfies(a -> assertThat(a.getUsuario()).as("check usuario").isEqualTo(expected.getUsuario()));
    }
}
