package com.mycompany.playmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacionAllPropertiesEquals(Notificacion expected, Notificacion actual) {
        assertNotificacionAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacionAllUpdatablePropertiesEquals(Notificacion expected, Notificacion actual) {
        assertNotificacionUpdatableFieldsEquals(expected, actual);
        assertNotificacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacionAutoGeneratedPropertiesEquals(Notificacion expected, Notificacion actual) {
        assertThat(actual)
            .as("Verify Notificacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacionUpdatableFieldsEquals(Notificacion expected, Notificacion actual) {
        assertThat(actual)
            .as("Verify Notificacion relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getMensaje()).as("check mensaje").isEqualTo(expected.getMensaje()))
            .satisfies(a -> assertThat(a.getLeida()).as("check leida").isEqualTo(expected.getLeida()))
            .satisfies(a -> assertThat(a.getFechaEnvio()).as("check fechaEnvio").isEqualTo(expected.getFechaEnvio()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacionUpdatableRelationshipsEquals(Notificacion expected, Notificacion actual) {
        assertThat(actual)
            .as("Verify Notificacion relationships")
            .satisfies(a -> assertThat(a.getDestinatario()).as("check destinatario").isEqualTo(expected.getDestinatario()));
    }
}
