package com.mycompany.playmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NoticiaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoticiaAllPropertiesEquals(Noticia expected, Noticia actual) {
        assertNoticiaAutoGeneratedPropertiesEquals(expected, actual);
        assertNoticiaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoticiaAllUpdatablePropertiesEquals(Noticia expected, Noticia actual) {
        assertNoticiaUpdatableFieldsEquals(expected, actual);
        assertNoticiaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoticiaAutoGeneratedPropertiesEquals(Noticia expected, Noticia actual) {
        assertThat(actual)
            .as("Verify Noticia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoticiaUpdatableFieldsEquals(Noticia expected, Noticia actual) {
        assertThat(actual)
            .as("Verify Noticia relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getContenido()).as("check contenido").isEqualTo(expected.getContenido()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getFechaPublicacion()).as("check fechaPublicacion").isEqualTo(expected.getFechaPublicacion()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoticiaUpdatableRelationshipsEquals(Noticia expected, Noticia actual) {
        assertThat(actual)
            .as("Verify Noticia relationships")
            .satisfies(a -> assertThat(a.getAutor()).as("check autor").isEqualTo(expected.getAutor()));
    }
}
