package com.mycompany.playmatch.domain;

import static com.mycompany.playmatch.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class PartidoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartidoAllPropertiesEquals(Partido expected, Partido actual) {
        assertPartidoAutoGeneratedPropertiesEquals(expected, actual);
        assertPartidoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartidoAllUpdatablePropertiesEquals(Partido expected, Partido actual) {
        assertPartidoUpdatableFieldsEquals(expected, actual);
        assertPartidoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartidoAutoGeneratedPropertiesEquals(Partido expected, Partido actual) {
        assertThat(actual)
            .as("Verify Partido auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartidoUpdatableFieldsEquals(Partido expected, Partido actual) {
        assertThat(actual)
            .as("Verify Partido relevant properties")
            .satisfies(a ->
                assertThat(a.getFechaHora())
                    .as("check fechaHora")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaHora())
            )
            .satisfies(a -> assertThat(a.getLugar()).as("check lugar").isEqualTo(expected.getLugar()))
            .satisfies(a -> assertThat(a.getTiempoMinutos()).as("check tiempoMinutos").isEqualTo(expected.getTiempoMinutos()))
            .satisfies(a -> assertThat(a.getMarcadorLocal()).as("check marcadorLocal").isEqualTo(expected.getMarcadorLocal()))
            .satisfies(a -> assertThat(a.getMarcadorVisitante()).as("check marcadorVisitante").isEqualTo(expected.getMarcadorVisitante()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartidoUpdatableRelationshipsEquals(Partido expected, Partido actual) {
        assertThat(actual)
            .as("Verify Partido relationships")
            .satisfies(a -> assertThat(a.getEquipolocal()).as("check equipolocal").isEqualTo(expected.getEquipolocal()))
            .satisfies(a -> assertThat(a.getEquipovisitante()).as("check equipovisitante").isEqualTo(expected.getEquipovisitante()))
            .satisfies(a -> assertThat(a.getTorneo()).as("check torneo").isEqualTo(expected.getTorneo()));
    }
}
