package com.mycompany.playmatch.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TablaPosicionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTablaPosicionAllPropertiesEquals(TablaPosicion expected, TablaPosicion actual) {
        assertTablaPosicionAutoGeneratedPropertiesEquals(expected, actual);
        assertTablaPosicionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTablaPosicionAllUpdatablePropertiesEquals(TablaPosicion expected, TablaPosicion actual) {
        assertTablaPosicionUpdatableFieldsEquals(expected, actual);
        assertTablaPosicionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTablaPosicionAutoGeneratedPropertiesEquals(TablaPosicion expected, TablaPosicion actual) {
        assertThat(actual)
            .as("Verify TablaPosicion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTablaPosicionUpdatableFieldsEquals(TablaPosicion expected, TablaPosicion actual) {
        assertThat(actual)
            .as("Verify TablaPosicion relevant properties")
            .satisfies(a -> assertThat(a.getPuntos()).as("check puntos").isEqualTo(expected.getPuntos()))
            .satisfies(a -> assertThat(a.getPartidosJugados()).as("check partidosJugados").isEqualTo(expected.getPartidosJugados()))
            .satisfies(a -> assertThat(a.getPartidosGanados()).as("check partidosGanados").isEqualTo(expected.getPartidosGanados()))
            .satisfies(a -> assertThat(a.getPartidosEmpatados()).as("check partidosEmpatados").isEqualTo(expected.getPartidosEmpatados()))
            .satisfies(a -> assertThat(a.getPartidosPerdidos()).as("check partidosPerdidos").isEqualTo(expected.getPartidosPerdidos()))
            .satisfies(a -> assertThat(a.getGolesFavor()).as("check golesFavor").isEqualTo(expected.getGolesFavor()))
            .satisfies(a -> assertThat(a.getGolesContra()).as("check golesContra").isEqualTo(expected.getGolesContra()))
            .satisfies(a -> assertThat(a.getDiferenciaGoles()).as("check diferenciaGoles").isEqualTo(expected.getDiferenciaGoles()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTablaPosicionUpdatableRelationshipsEquals(TablaPosicion expected, TablaPosicion actual) {
        assertThat(actual)
            .as("Verify TablaPosicion relationships")
            .satisfies(a -> assertThat(a.getGrupo()).as("check grupo").isEqualTo(expected.getGrupo()))
            .satisfies(a -> assertThat(a.getTorneo()).as("check torneo").isEqualTo(expected.getTorneo()));
    }
}
