package com.mycompany.playmatch.domain;

import static com.mycompany.playmatch.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class TorneoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTorneoAllPropertiesEquals(Torneo expected, Torneo actual) {
        assertTorneoAutoGeneratedPropertiesEquals(expected, actual);
        assertTorneoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTorneoAllUpdatablePropertiesEquals(Torneo expected, Torneo actual) {
        assertTorneoUpdatableFieldsEquals(expected, actual);
        assertTorneoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTorneoAutoGeneratedPropertiesEquals(Torneo expected, Torneo actual) {
        assertThat(actual)
            .as("Verify Torneo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTorneoUpdatableFieldsEquals(Torneo expected, Torneo actual) {
        assertThat(actual)
            .as("Verify Torneo relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getFechaInicio()).as("check fechaInicio").isEqualTo(expected.getFechaInicio()))
            .satisfies(a -> assertThat(a.getFechaFin()).as("check fechaFin").isEqualTo(expected.getFechaFin()))
            .satisfies(a ->
                assertThat(a.getHoraInicio())
                    .as("check horaInicio")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getHoraInicio())
            )
            .satisfies(a -> assertThat(a.getUbicacion()).as("check ubicacion").isEqualTo(expected.getUbicacion()))
            .satisfies(a -> assertThat(a.getReglamento()).as("check reglamento").isEqualTo(expected.getReglamento()))
            .satisfies(a ->
                assertThat(a.getReglamentoContentType()).as("check reglamento content type").isEqualTo(expected.getReglamentoContentType())
            )
            .satisfies(a -> assertThat(a.getCupoMaximoEquipos()).as("check cupoMaximoEquipos").isEqualTo(expected.getCupoMaximoEquipos()))
            .satisfies(a ->
                assertThat(a.getCupoMaximoJugadores()).as("check cupoMaximoJugadores").isEqualTo(expected.getCupoMaximoJugadores())
            )
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTorneoUpdatableRelationshipsEquals(Torneo expected, Torneo actual) {
        assertThat(actual)
            .as("Verify Torneo relationships")
            .satisfies(a -> assertThat(a.getCategoria()).as("check categoria").isEqualTo(expected.getCategoria()));
    }
}
